//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitML.JsonVM.ConsoleTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VitML.JsonVM.ConsoleTest.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;$schema&quot;:&quot;http://json-schema.org/draft-04/schema#&quot;,
        ///    &quot;id&quot;:&quot;http://vit.com.ua/edgeserver/compositor#&quot;,
        ///
        ///    &quot;type&quot;:&quot;object&quot;,
        ///	&apos;format&apos;:&apos;tab&apos;,
        ///
        ///	&apos;definitions&apos; : {
        ///		
        ///	},
        ///
        ///    &quot;properties&quot;:{
        ///
        ///        &quot;Source&quot;:{
        ///
        ///            &quot;id&quot;:&quot;Source&quot;,
        ///            &quot;type&quot;:&quot;object&quot;,
        ///
        ///            &quot;properties&quot;:{
        ///
        ///                &quot;MasterName&quot;:{
        ///                    &quot;id&quot;:&quot;MasterName&quot;,
        ///                    &quot;type&quot;: [&quot;string&quot;, &quot;null&quot;],
        ///					&apos;format&apos;:&apos;label&apos;,
        ///                },
        ///
        ///				&quot;SetMaster&quot;:{
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string compositor_schema {
            get {
                return ResourceManager.GetString("compositor_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///	&quot;id&quot; : &quot;http://vit.com.ua/edgeserver/core#&quot;,
        ///	&quot;$schema&quot;: &quot;http://json-schema.org/draft-04/schema#&quot;,
        ///
        ///	&apos;definitions&apos; : {
        ///		
        ///		&apos;uint&apos; : {
        ///			
        ///			&apos;type&apos; : &apos;integer&apos;,
        ///			&apos;minimum&apos; : 0,
        ///		},
        ///	}
        ///}.
        /// </summary>
        internal static string core {
            get {
                return ResourceManager.GetString("core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///	&quot;id&quot; : &quot;http://vit.com.ua/edgeserver/definitions#&quot;,
        ///	&quot;$schema&quot;: &quot;http://json-schema.org/draft-04/schema#&quot;,
        ///
        ///	&apos;definitions&apos; : {
        ///		
        ///		&apos;EventDir&apos; : {
        ///			
        ///			&apos;type&apos; : &apos;object&apos;,
        ///
        ///			&apos;properties&apos; : {
        ///                      
        ///				&quot;Prefix&quot;:{
        ///					&apos;type&apos; : &apos;string&apos;,
        ///				},                            
        ///				&quot;Suffix&quot;:{
        ///					&apos;type&apos; : &apos;string&apos;,
        ///				},                              
        ///				&quot;Dir&quot;:{
        ///					&apos;type&apos; : &apos;string&apos;,
        ///				}
        ///			},
        ///
        ///			&quot;required&quot; : [ &apos;Prefix&apos;, &apos;Suffix&apos;, &apos;Dir&apos; ],
        ///		},
        ///
        ///		&apos;FrameReac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string definitions {
            get {
                return ResourceManager.GetString("definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;$schema&quot;:&quot;http://json-schema.org/draft-04/schema#&quot;,
        ///    &quot;id&quot;:&quot;http://vit.com.ua/edgeserver/drivers&quot;,
        ///
        ///	&apos;definitions&apos; : {
        ///
        ///		&apos;smartmicro39&apos; : {
        ///
        ///			&quot;type&quot;:&quot;object&quot;,
        ///
        ///			&quot;properties&quot;:{
        ///
        ///				&quot;PosX&quot;:{
        ///					&quot;id&quot;:&quot;PosX&quot;,
        ///					&quot;type&quot;:&quot;integer&quot;
        ///				},
        ///				&quot;PosY&quot;:{
        ///					&quot;id&quot;:&quot;PosY&quot;,
        ///					&quot;type&quot;:&quot;integer&quot;
        ///				},
        ///				&quot;PosZ&quot;:{
        ///					&quot;id&quot;:&quot;PosZ&quot;,
        ///					&quot;type&quot;:&quot;integer&quot;
        ///				},
        ///				&quot;PosH&quot;:{
        ///					&quot;id&quot;:&quot;PosH&quot;,
        ///					&quot;type&quot;:&quot;integer&quot;
        ///				},
        ///				&quot;AngleXY&quot;:{
        ///					&quot;id&quot;:&quot;AngleXY&quot;,
        ///					&quot;type&quot;:&quot;i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string drivers {
            get {
                return ResourceManager.GetString("drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// {
        ///	&quot;id&quot; : &quot;http://vit.com.ua/edgeserver/eventstore#&quot;,
        ///	&quot;$schema&quot;: &quot;http://json-schema.org/draft-04/schema#&quot;,
        ///
        ///	&quot;title&quot; : &quot;EventStore main.xconf&quot;,
        ///	&quot;type&quot; : &quot;object&quot;,
        ///
        ///	&apos;format&apos; : &apos;tab&apos;,
        ///
        ///	&quot;definitions&quot; : {
        ///
        ///		&quot;DbStore.ParamSet&quot; : {
        ///
        ///			&quot;type&quot; : &quot;object&quot;,
        ///
        ///			&quot;properties&quot;: {
        ///					
        ///				&quot;DbHost&quot;: {
        ///					&quot;title&quot; : &quot;Host&quot;,
        ///					&quot;type&quot;: &quot;string&quot;,
        ///					&quot;format&quot;: &quot;ipv4&quot;,
        ///					&quot;default&quot;: &quot;127.0.0.1&quot;,
        ///					&quot;binding&quot; : {
        ///						&quot;path&quot; : &quot;DbHost&quot;
        ///					}
        ///				},
        ///				&quot;DbPort&quot;: {
        ///					&quot;title&quot; : [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eventstore_schema {
            get {
                return ResourceManager.GetString("eventstore_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;$schema&quot;:&quot;http://json-schema.org/draft-04/schema#&quot;,
        ///    &quot;id&quot;:&quot;http://vit.com.ua/edgeserver/grabcontrol#&quot;,
        ///
        ///    &quot;type&quot;:&quot;object&quot;,
        ///	&apos;format&apos; : &apos;tab&apos;,
        ///
        ///    &quot;properties&quot;:{
        ///
        ///        &quot;Analyzer&quot;:{
        ///            &quot;id&quot;:&quot;Analyzer&quot;,
        ///            &quot;type&quot;:&quot;object&quot;,
        ///
        ///            &quot;properties&quot;:{
        ///
        ///                &quot;ParamSet&quot;:{
        ///                    &quot;id&quot;:&quot;ParamSet&quot;,
        ///                    &quot;type&quot;:&quot;object&quot;,
        ///
        ///                    &quot;properties&quot;:{
        ///
        ///                        &quot;Target&quot;:{
        ///                            &quot;id&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string grabcontrol_schema {
            get {
                return ResourceManager.GetString("grabcontrol_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;$schema&quot;:&quot;http://json-schema.org/draft-04/schema#&quot;,
        ///    &quot;id&quot;:&quot;http://vit.com.ua/edgeserver/lpr#&quot;,
        ///
        ///    &quot;type&quot;:&quot;object&quot;,
        ///	&apos;format&apos; : &apos;tab&apos;,
        ///
        ///    &quot;properties&quot;:{
        ///
        ///        &quot;media-source&quot;:{
        ///
        ///            &quot;id&quot;:&quot;media-source&quot;,
        ///            &quot;type&quot;:&quot;object&quot;,
        ///
        ///            &quot;properties&quot;:{
        ///
        ///                &quot;data_input_dir&quot;:{
        ///                    &quot;id&quot;:&quot;data_input_dir&quot;,
        ///                    &quot;type&quot;:&quot;string&quot;
        ///                },
        ///                &quot;meta_input_dir&quot;:{
        ///                    &quot;id&quot;:&quot;meta_input_di [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lpr_schema {
            get {
                return ResourceManager.GetString("lpr_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;id&quot; : &quot;http://vit.com.ua/edgeserver/mediacodec#&quot;,
        ///	&quot;$schema&quot;: &quot;http://json-schema.org/draft-04/schema#&quot;,
        ///
        ///	&apos;title&apos; : &apos;MediaCodec main.conf&apos;,
        ///	&apos;type&apos; : &apos;object&apos;,
        ///
        ///	&apos;definitions&apos; : {
        ///		
        ///		&apos;FrameParamSet&apos; : {
        ///			
        ///			&apos;type&apos; : &apos;object&apos;,
        ///
        ///			&apos;properties&apos; : {
        ///
        ///				&quot;FrameMeta&quot;: {&apos;$ref&apos; : &apos;definitions#/definitions/EventDir&apos;},
        ///				&quot;FrameData&quot;: {&apos;$ref&apos; : &apos;definitions#/definitions/EventDir&apos;},
        ///			},
        ///
        ///			&quot;required&quot; : [ &apos;FrameMeta&apos;, &quot;FrameData&quot; ],
        ///			&quot;additionalProperties&quot;: false,
        ///		},
        ///	},
        ///
        ///	&apos;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mediacodec_schema {
            get {
                return ResourceManager.GetString("mediacodec_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;$schema&quot;:&quot;http://json-schema.org/draft-04/schema#&quot;,
        ///    &quot;id&quot;:&quot;http://vit.com.ua/edgeserver/mediagrabber#&quot;,
        ///
        ///    &quot;type&quot;:&quot;object&quot;,
        ///
        ///    &quot;properties&quot;:{
        ///
        ///        &quot;TxPipes&quot;:{
        ///            &quot;id&quot;:&quot;TxPipes&quot;,
        ///            &quot;type&quot;:&quot;array&quot;,
        ///
        ///            &quot;items&quot;: {
        ///                    &quot;type&quot;:&quot;string&quot;
        ///            },
        ///
        ///			&quot;default&quot; : &quot;&quot;,
        ///        },
        ///
        ///        &quot;Driver&quot;:{
        ///            &quot;id&quot;:&quot;Driver&quot;,
        ///            &quot;type&quot;:&quot;object&quot;,
        ///
        ///            &quot;properties&quot;:{
        ///                &quot;Vendor&quot;:{
        ///                  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mediagrabber_schema {
            get {
                return ResourceManager.GetString("mediagrabber_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///	&quot;id&quot; : &quot;http://vit.com.ua/edgeserver/mediastore#&quot;,
        ///	&quot;$schema&quot;: &quot;http://json-schema.org/draft-04/schema#&quot;,
        ///
        ///	&apos;title&apos; : &apos;MediaStore main.conf&apos;,
        ///	&apos;type&apos; : &apos;object&apos;,
        ///
        ///	&apos;definitions&apos; : {
        ///
        ///		
        ///
        ///		&apos;Store.ParamSet&apos; : {
        ///			
        ///			&apos;type&apos; : &apos;object&apos;,
        ///
        ///			&apos;properties&apos; : {
        ///				
        ///				&quot;RootDir&quot;: {
        ///					&apos;type&apos; : &apos;string&apos;
        ///				},
        ///				&quot;Channels&quot;: { 
        ///
        ///					&apos;type&apos; : &apos;array&apos;,
        ///
        ///					&quot;items&quot; : {
        ///						
        ///						&quot;title&quot; : &quot;item&quot;,
        ///						&quot;type&quot; : &quot;object&quot;,
        ///
        ///						&quot;properties&quot; : 
        ///						{
        ///							&quot;Name&quot;: { 
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mediastore_schema {
            get {
                return ResourceManager.GetString("mediastore_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;id&quot; : &quot;http://vit.com.ua/edgeserver/radar&quot;,
        ///	&quot;$schema&quot;: &quot;http://json-schema.org/draft-04/schema#&quot;,
        ///
        ///	&quot;title&quot; : &quot;Radar main.conf&quot;,
        ///
        ///	&apos;definitions&apos; : {
        ///
        ///		&apos;QueueSetObject&apos; : {
        ///
        ///			&apos;type&apos; : &apos;object&apos;,
        ///
        ///			&apos;properties&apos; : {
        ///
        ///				&quot;QueueSet&quot;:	{ 
        ///
        ///					&apos;type&apos; : &apos;array&apos;,
        ///
        ///					&apos;items&apos; : {
        ///
        ///						&apos;type&apos; : &apos;object&apos;,
        ///
        ///						&apos;properties&apos; : {
        ///
        ///							&quot;File&quot;: {
        ///								&apos;type&apos; : &apos;string&apos;
        ///							},
        ///
        ///							&quot;ParamSet&quot; : {
        ///								&apos;type&apos; : &apos;object&apos;,
        ///								&apos;oneOf&apos; : [{&apos;$ref&apos;:&apos;definitions#/def [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string radar_schema {
            get {
                return ResourceManager.GetString("radar_schema", resourceCulture);
            }
        }
    }
}
